#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$ROOT/config/ragflow.env"
umask 077

banner "Nova Avatar · RAGFlow 本機安裝"

stage "安裝 Docker 與 Compose"
say "套件安裝會在本機終端要求 sudo 密碼；本引導程式不讀取或保存密碼。"
step "確認本機 Docker 與 Compose；若尚未安裝，依現有套件來源安裝。"
if confirm "現在安裝 Docker？"; then
  bash "$ROOT/scripts/ragflow.sh" install-docker
else
  warn "未安裝 Docker；先完成本階段再重新執行此引導程式。"
  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  warn "Docker 尚未可用。若剛安裝完成，請重新登入本機終端，再重跑此引導程式。"
  exit 1
fi
pause "Docker 已就緒。按 Enter 繼續。"

stage "啟動獨立 RAGFlow 與嵌入服務"
step "此步會拉取映像並啟動 nova-ragflow，不會重啟 Nova Avatar。"
if confirm "現在啟動 RAGFlow？"; then
  bash "$ROOT/scripts/ragflow.sh" pull-model
  bash "$ROOT/scripts/ragflow.sh" up
  bash "$ROOT/scripts/ragflow.sh" status
else
  warn "服務未啟動；可稍後執行 bash scripts/ragflow.sh up。"
  exit 1
fi
pause "確認容器運作後按 Enter 繼續。"

stage "在 RAGFlow 登入並設定專用嵌入模型"
open_url "http://127.0.0.1:8088"
step "在本機瀏覽器登入 RAGFlow。初始管理密碼可在 .local/ragflow/upstream/docker/.env 的 ADMIN_DEFAULT_PASSWORD 欄位讀取，請立即更改。"
step "進入使用者設定 → Model providers，選 Ollama 並建立獨立執行個體。"
step "服務位址填 http://host.docker.internal:11435；加入 bge-m3，類型選 Embedding。"
note "這是獨立 CPU 嵌入程序；Nova 原有 127.0.0.1:11434 與 llama.cpp 不變。"
pause "確認 bge-m3 在 RAGFlow 中可用後按 Enter。"

stage "建立知識庫與解析文件"
open_url "http://127.0.0.1:8088"
step "建立知識庫，選擇 bge-m3 嵌入模型。"
step "上傳要提供數位人的文件，啟動解析並等待解析完成。"
note "若目前沒有文件，可稍後再做；Nova 的 RAG 設定先保持關閉。"
pause "文件已解析完成，或決定稍後匯入時，按 Enter。"

stage "建立 API 金鑰並寫入 Nova 後端"
open_url "http://127.0.0.1:8088"
step "點右上角頭像進入設定，切換到 API 頁，建立並複製 RAGFlow API key。"
ask_secret NOVA_RAGFLOW_API_KEY "在這台主機的終端貼上 API key（輸入不顯示）："
if [[ -z "$NOVA_RAGFLOW_API_KEY" ]]; then
  warn "API key 為空；未寫入後端設定。"
  exit 1
fi
write_env NOVA_RAGFLOW_URL "http://127.0.0.1:9380"
write_env NOVA_RAGFLOW_API_KEY "$NOVA_RAGFLOW_API_KEY"
chmod 600 "$ENV_FILE"
unset NOVA_RAGFLOW_API_KEY
note "金鑰只寫入被 Git 忽略的 config/ragflow.env；沒有傳送到聊天或瀏覽器。"
pause "後端設定已保存。按 Enter 繼續。"

stage "在 Nova 控制台驗證"
step "重啟 Nova 後端或 start-all.sh，讓新的私有環境設定生效。"
step "在控制台的「知識庫檢索」頁，確認顯示 RAGFlow 已連線。"
step "為目前數位人選知識庫，儲存後先測試檢索，再啟用並試一輪文字或語音。"
note "若未建立文件，先保持 RAG 關閉；既有回答功能不受影響。"
pause "確認完成後按 Enter 查看摘要。"

finish
