# Derived from Kedreamix/Linly-Talker-Stream.
# Licensed under the Apache License, Version 2.0.
# Modified by HongXian0903, 2026. See LICENSE and NOTICE.

"""路由模組"""
from .webrtc import offer
from .chat import human, interrupt_talk, is_speaking, clear_history
from .audio import humanaudio, asr
from .video import set_audiotype, record, download_record
from .health import health_check
from .voice_tests import list_voice_tests, run_voice_test, clear_voice_tests
from .ragflow import (
    get_ragflow_settings,
    put_ragflow_settings,
    list_ragflow_datasets,
    test_ragflow_retrieval,
)
from .settings import (
    get_settings,
    get_vad_settings,
    set_vad_settings,
    get_speech_settings,
    set_stt_settings,
    set_tts_settings,
    pick_speech_path,
    get_stage_settings,
    set_stage_settings,
    get_backgrounds,
    upload_background,
    select_background,
    background_preview,
    delete_background,
    archived_backgrounds,
    restore_archived_background,
    list_llm_models,
    set_llm_model,
    get_llm_rules,
    set_llm_rules,
    set_avatar,
    set_mouth_quality,
    avatar_preview,
    avatar_scene_preview,
    delete_avatar,
    archived_avatars,
    restore_archived_avatar,
    delete_archived_avatar_permanently,
    import_avatar,
    import_avatar_status,
)

__all__ = [
    'offer',
    'human',
    'interrupt_talk', 
    'is_speaking',
    'clear_history',
    'humanaudio',
    'asr',
    'set_audiotype',
    'record',
    'download_record',
    'health_check',
    'list_voice_tests',
    'run_voice_test',
    'clear_voice_tests',
    'get_ragflow_settings',
    'put_ragflow_settings',
    'list_ragflow_datasets',
    'test_ragflow_retrieval',
    'get_settings',
    'get_vad_settings',
    'set_vad_settings',
    'get_speech_settings',
    'set_stt_settings',
    'set_tts_settings',
    'pick_speech_path',
    'get_stage_settings',
    'set_stage_settings',
    'get_backgrounds',
    'upload_background',
    'select_background',
    'background_preview',
    'delete_background',
    'archived_backgrounds',
    'restore_archived_background',
    'list_llm_models',
    'set_llm_model',
    'get_llm_rules',
    'set_llm_rules',
    'set_avatar',
    'set_mouth_quality',
    'avatar_preview',
    'avatar_scene_preview',
    'delete_avatar',
    'archived_avatars',
    'restore_archived_avatar',
    'delete_archived_avatar_permanently',
    'import_avatar',
    'import_avatar_status',
]
